# Setup
title: My Jekyll Site
tagline:
url: http://localhost:4000
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name:
  url:
  email:

# Custom vars
version: 1.0.0
